# Generated by Django 4.2.26 on 2025-11-30 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_bag', models.DecimalField(decimal_places=2, help_text='Price per bag (GHS)', max_digits=10)),
                ('price_per_ton', models.DecimalField(decimal_places=2, help_text='Price per ton (GHS)', max_digits=12)),
                ('packaging_size', models.CharField(help_text='e.g., 50kg bag, 100kg bag', max_length=50)),
                ('market_notes', models.TextField(blank=True, help_text='Market conditions or notes')),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prices',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['product', 'is_current'], name='prices_product_5e9530_idx'), models.Index(fields=['effective_date'], name='prices_effecti_57c394_idx')],
                'unique_together': {('product', 'packaging_size', 'is_current')},
            },
        ),
    ]
