# Generated by Django 6.0.3 on 2026-03-15 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('products', '0002_alter_product_options_product_availability_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'is_current', 'price_per_ton'], name='prices_product_86ea6b_idx'),
        ),
    ]
