# Generated by Django 4.2.26 on 2025-11-30 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image_alt_text', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_posts_slug_b4ca25_idx'), models.Index(fields=['is_published', 'published_at'], name='blog_posts_is_publ_4325e6_idx'), models.Index(fields=['category'], name='blog_posts_categor_d08396_idx')],
            },
        ),
    ]
