# Generated by Django 4.2.26 on 2025-11-30 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0001_initial'),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bags', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_tons', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_type', models.CharField(choices=[('FARMER', 'Farmer Supply'), ('MARKET_PURCHASE', 'Market Purchase')], max_length=20)),
                ('quality_grade', models.CharField(default='Standard', max_length=50)),
                ('moisture_content', models.DecimalField(decimal_places=2, help_text='Moisture percentage', max_digits=5)),
                ('warehouse_location', models.CharField(max_length=200)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateTimeField()),
                ('expiry_alert_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='farmers.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product')),
            ],
            options={
                'db_table': 'stock',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ADDITION', 'Addition'), ('DEDUCTION', 'Deduction'), ('TRANSFER', 'Transfer'), ('DAMAGE', 'Damage/Loss')], max_length=20)),
                ('quantity_bags', models.IntegerField()),
                ('quantity_tons', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stock')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', 'movement_type'], name='stock_movem_stock_i_02a5ef_idx'), models.Index(fields=['created_at'], name='stock_movem_created_07bdcc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse_location'], name='stock_product_a4dde1_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['date_received'], name='stock_date_re_502c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['expiry_alert_date'], name='stock_expiry__a439bd_idx'),
        ),
    ]
