# Generated by Django 6.0.3 on 2026-03-15 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'benefit_sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_location_text', models.TextField(blank=True)),
                ('office_map_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'footer_contacts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_farmers_count', models.PositiveIntegerField(default=0)),
                ('avg_delivery_window', models.CharField(default='24-48 hours', max_length=100)),
                ('repeat_customer_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hero_metrics',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('role_or_business', models.CharField(blank=True, max_length=255)),
                ('quote', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_featured', 'is_published'], name='testimonial_is_feat_b35cd0_idx'), models.Index(fields=['created_at'], name='testimonial_created_60b22d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BenefitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homepage.benefitsection')),
            ],
            options={
                'db_table': 'benefit_items',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['section', 'display_order'], name='benefit_ite_section_eb7176_idx')],
            },
        ),
    ]
