# Generated by Django 4.2.26 on 2025-11-30 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='farmer_profiles/')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='GH', unique=True)),
                ('ghana_card_number', models.CharField(help_text='Ghana Card Number (e.g., GHA-123456789-0)', max_length=20, unique=True)),
                ('gps_latitude', models.DecimalField(decimal_places=6, help_text='GPS Latitude', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('gps_longitude', models.DecimalField(decimal_places=6, help_text='GPS Longitude', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('community', models.CharField(max_length=100)),
                ('maize_types_supplied', models.JSONField(default=list, help_text='List of maize types supplied (e.g., ["Yellow Maize", "White Maize"])')),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'farmers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bags', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_tons', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('date_delivered', models.DateTimeField()),
                ('cost_per_bag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='farmers.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farmer Supplies',
                'db_table': 'farmer_supplies',
                'ordering': ['-date_delivered'],
            },
        ),
    ]
