# Generated by Django 4.2.26 on 2025-11-30 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersupply',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_supplies', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='farmersupply',
            index=models.Index(fields=['farmer', 'date_delivered'], name='farmer_supp_farmer__be76f3_idx'),
        ),
        migrations.AddIndex(
            model_name='farmersupply',
            index=models.Index(fields=['payment_status'], name='farmer_supp_payment_ef6f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='farmersupply',
            index=models.Index(fields=['product'], name='farmer_supp_product_2d17a9_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['mobile_number'], name='farmers_mobile__353700_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['ghana_card_number'], name='farmers_ghana_c_1cc3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['region', 'district'], name='farmers_region_12d62a_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['is_approved', 'is_active'], name='farmers_is_appr_da7e81_idx'),
        ),
    ]
