# Generated by Django 4.2.26 on 2025-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name (e.g., Yellow Maize, White Maize)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('packaging_sizes', models.JSONField(default=list, help_text='List of available packaging sizes (e.g., ["50kg bag", "100kg bag", "1 ton"])')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_name_6f9890_idx'), models.Index(fields=['is_available'], name='products_is_avai_39744e_idx')],
            },
        ),
    ]
